version: "3.5"
services:
  mysql-consumer:
    build: ./mysql-consumer
    depends_on:
    - mysql-server
    restart: unless-stopped
  mysql-server:
    build: ./mysql-server
    environment:
    - MYSQL_ROOT_PASSWORD=root
    restart: unless-stopped
  mongodb-server:
    image: mongo:4.0
    restart: unless-stopped
  mysql-cli:
    build: ./mysql-cli
    depends_on:
    - mysql-server
    command: [/bin/false]
  mongodb-fetcher:
    build: ./mongodb-fetcher
    depends_on:
    - mongodb-server
